//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ImportPermitPortal.EF.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Address
    {
        public Address()
        {
            this.ImporterAddresses = new HashSet<ImporterAddress>();
        }
    
        public long AddressId { get; set; }
        public string AddressLine1 { get; set; }
        public string AddressLine2 { get; set; }
        public string LastUpdated { get; set; }
        public long CityId { get; set; }
    
        public virtual City City { get; set; }
        public virtual ICollection<ImporterAddress> ImporterAddresses { get; set; }
    }
}
