//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ImportPermitPortal.EF.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class ApplicationContent
    {
        public int Id { get; set; }
        public string Title { get; set; }
        public string BodyContent { get; set; }
        public string Href { get; set; }
        public bool IsInUse { get; set; }
    }
}
