//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ImportPermitPortal.EF.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Application
    {
        public Application()
        {
            this.ApplicationDocuments = new HashSet<ApplicationDocument>();
            this.ApplicationIssues = new HashSet<ApplicationIssue>();
            this.ApplicationItems = new HashSet<ApplicationItem>();
            this.ApplicationLicenseMappings = new HashSet<ApplicationLicenseMapping>();
            this.ImportApplicationHistories = new HashSet<ImportApplicationHistory>();
            this.PermitApplications = new HashSet<PermitApplication>();
            this.ProcessingHistories = new HashSet<ProcessingHistory>();
            this.ProcessTrackings = new HashSet<ProcessTracking>();
            this.SignOffDocuments = new HashSet<SignOffDocument>();
        }
    
        public long Id { get; set; }
        public long ImporterId { get; set; }
        public long DerivedTotalQUantity { get; set; }
        public double DerivedValue { get; set; }
        public int ApplicationStatusCode { get; set; }
        public System.DateTime DateApplied { get; set; }
        public System.DateTime LastModified { get; set; }
        public int ClassificationId { get; set; }
        public long InvoiceId { get; set; }
        public string PreviousPermitNo { get; set; }
        public int ApplicationTypeId { get; set; }
    
        public virtual ApplicationType ApplicationType { get; set; }
        public virtual Importer Importer { get; set; }
        public virtual Invoice Invoice { get; set; }
        public virtual ICollection<ApplicationDocument> ApplicationDocuments { get; set; }
        public virtual ICollection<ApplicationIssue> ApplicationIssues { get; set; }
        public virtual ICollection<ApplicationItem> ApplicationItems { get; set; }
        public virtual ICollection<ApplicationLicenseMapping> ApplicationLicenseMappings { get; set; }
        public virtual ICollection<ImportApplicationHistory> ImportApplicationHistories { get; set; }
        public virtual ICollection<PermitApplication> PermitApplications { get; set; }
        public virtual ICollection<ProcessingHistory> ProcessingHistories { get; set; }
        public virtual ICollection<ProcessTracking> ProcessTrackings { get; set; }
        public virtual ICollection<SignOffDocument> SignOffDocuments { get; set; }
    }
}
