//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ImportPermitPortal.EF.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class ApplicationItem
    {
        public ApplicationItem()
        {
            this.ApplicationCountries = new HashSet<ApplicationCountry>();
            this.ProductBankers = new HashSet<ProductBanker>();
            this.ThroughPuts = new HashSet<ThroughPut>();
        }
    
        public long Id { get; set; }
        public long ApplicationId { get; set; }
        public long ProductId { get; set; }
        public long EstimatedQuantity { get; set; }
        public double EstimatedValue { get; set; }
        public string PSFNumber { get; set; }
        public string ReferenceLicenseCode { get; set; }
        public double TotalImportedQuantity { get; set; }
        public double ImportedQuantityValue { get; set; } 
        public double OutstandingQuantity { get; set; }
        public Nullable<System.DateTime> DateImported { get; set; }
        public int StorageProviderTypeId { get; set; }
    
        public virtual Application Application { get; set; }
        public virtual ICollection<ApplicationCountry> ApplicationCountries { get; set; }
        public virtual Product Product { get; set; }
        public virtual StorageProviderType StorageProviderType { get; set; }
        public virtual ICollection<ProductBanker> ProductBankers { get; set; }
        public virtual ICollection<ThroughPut> ThroughPuts { get; set; }
    }
}

