//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ImportPermitPortal.EF.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class ApplicationDepot
    {
        public long Id { get; set; }
        public long ApplicationItemId { get; set; }
        public int DepotId { get; set; }
        public Nullable<long> ThroughputId { get; set; }
        public long ProductId { get; set; }
    
        public virtual Depot Depot { get; set; }
        public virtual Product Product { get; set; }
    }
}
