//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ImportPermitPortal.EF.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class BankBranch
    {
        public BankBranch()
        {
            this.BankUsers = new HashSet<BankUser>();
        }
    
        public int Id { get; set; }
        public string Name { get; set; }
        public string BranchCode { get; set; }
        public int BankId { get; set; }
    
        public virtual Bank Bank { get; set; }
        public virtual ICollection<BankUser> BankUsers { get; set; }
    }
}
