//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ImportPermitPortal.EF.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class BillOfLadingData
    {
        public long Id { get; set; }
        public long NotificationInspectionId { get; set; }
        public int LabParameterId { get; set; }
        public double ValueIndicated { get; set; }
    
        public virtual LabParameter LabParameter { get; set; }
        public virtual NotificationInspection NotificationInspection { get; set; }
    }
}
