//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ImportPermitPortal.EF.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Calculator
    {
        public int Id { get; set; }
        public double QuantityInCountry { get; set; }
        public double QuantityTrunkedOut { get; set; }
        public long Counter { get; set; }
    }
}
