//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ImportPermitPortal.EF.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class DocumentIssue
    {
        public long Id { get; set; }
        public long DocumentId { get; set; }
        public string Description { get; set; }
        public System.DateTime IssueDate { get; set; }
        public int IssueTypeId { get; set; }
        public long FiledById { get; set; }
        public int Status { get; set; }
    
        public virtual Document Document { get; set; }
        public virtual IssueType IssueType { get; set; }
        public virtual UserProfile UserProfile { get; set; }
    }
}
