//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ImportPermitPortal.EF.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class EmployeeDesk
    {
        public EmployeeDesk()
        {
            this.RecertificationResults = new HashSet<RecertificationResult>();
            this.NotificationHistories = new HashSet<NotificationHistory>();
            this.NotificationInspectionQueues = new HashSet<NotificationInspectionQueue>();
            this.ProcessingHistories = new HashSet<ProcessingHistory>();
            this.ProcessTrackings = new HashSet<ProcessTracking>();
            this.RecertificationHistories = new HashSet<RecertificationHistory>();
            this.RecertificationProcesses = new HashSet<RecertificationProcess>();
        }
    
        public long Id { get; set; }
        public long EmployeeId { get; set; }
        public int GroupId { get; set; }
        public Nullable<int> JobCount { get; set; }
        public Nullable<System.DateTime> CreatedAt { get; set; }
        public Nullable<System.DateTime> UpdatedAt { get; set; }
        public int ZoneId { get; set; }
        public int ActivityTypeId { get; set; }
        public Nullable<bool> IsUserAvailable { get; set; }
        public Nullable<int> ApplicationCount { get; set; }
        public Nullable<int> NotificationCount { get; set; }
        public Nullable<int> RecertificationCount { get; set; }
    
        public virtual Group Group { get; set; }
        public virtual StepActivityType StepActivityType { get; set; }
        public virtual UserProfile UserProfile { get; set; }
        public virtual Zone Zone { get; set; }
        public virtual ICollection<RecertificationResult> RecertificationResults { get; set; }
        public virtual ICollection<NotificationHistory> NotificationHistories { get; set; }
        public virtual ICollection<NotificationInspectionQueue> NotificationInspectionQueues { get; set; }
        public virtual ICollection<ProcessingHistory> ProcessingHistories { get; set; }
        public virtual ICollection<ProcessTracking> ProcessTrackings { get; set; }
        public virtual ICollection<RecertificationHistory> RecertificationHistories { get; set; }
        public virtual ICollection<RecertificationProcess> RecertificationProcesses { get; set; }
    }
}
