//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ImportPermitPortal.EF.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class ImporterAddress
    {
        public long ImporterAddressId { get; set; }
        public int AddressTypeId { get; set; }
        public long AddressId { get; set; }
        public long ImporterId { get; set; }
        public string LastUpdated { get; set; }
        public Nullable<bool> IsRegisteredSameAsOperational { get; set; }
    
        public virtual Address Address { get; set; }
        public virtual AddressType AddressType { get; set; }
        public virtual Importer Importer { get; set; }
    }
}
