//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ImportPermitPortal.EF.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Importer
    {
        public Importer()
        {
            this.Applications = new HashSet<Application>();
            this.Banks = new HashSet<Bank>();
            this.CompanyDocuments = new HashSet<CompanyDocument>();
            this.Depots = new HashSet<Depot>();
            this.Documents = new HashSet<Document>();
            this.ImporterAddresses = new HashSet<ImporterAddress>();
            this.Invoices = new HashSet<Invoice>();
            this.Notifications = new HashSet<Notification>();
            this.Permits = new HashSet<Permit>();
            this.People = new HashSet<Person>();
            this.ReferenceLicenses = new HashSet<ReferenceLicense>();
            this.StandardRequirements = new HashSet<StandardRequirement>();
        }
    
        public long Id { get; set; }
        public string Name { get; set; }
        public string TIN { get; set; }
        public string RCNumber { get; set; }
        public Nullable<int> StructureId { get; set; }
        public string LogoPath { get; set; }
        public bool IsActive { get; set; }
        public string DateAdded { get; set; }
        public string ShortNme { get; set; }
        public Nullable<int> TotalStaff { get; set; }
        public Nullable<int> TotalExpatriate { get; set; }
        public Nullable<System.DateTime> BusinessCommencementDate { get; set; }
    
        public virtual ICollection<Application> Applications { get; set; }
        public virtual ICollection<Bank> Banks { get; set; }
        public virtual ICollection<CompanyDocument> CompanyDocuments { get; set; }
        public virtual ICollection<Depot> Depots { get; set; }
        public virtual ICollection<Document> Documents { get; set; }
        public virtual Structure Structure { get; set; }
        public virtual ICollection<ImporterAddress> ImporterAddresses { get; set; }
        public virtual ICollection<Invoice> Invoices { get; set; }
        public virtual ICollection<Notification> Notifications { get; set; }
        public virtual ICollection<Permit> Permits { get; set; }
        public virtual ICollection<Person> People { get; set; }
        public virtual ICollection<ReferenceLicense> ReferenceLicenses { get; set; }
        public virtual ICollection<StandardRequirement> StandardRequirements { get; set; }
    }
}
