//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ImportPermitPortal.EF.Model
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class ImportPermitEntities : DbContext
    {
        public ImportPermitEntities()
            : base("name=ImportPermitEntities")
        {
            //Configuration.LazyLoadingEnabled = false;
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<C__MigrationHistory> C__MigrationHistory { get; set; }
        public virtual DbSet<AccountType> AccountTypes { get; set; }
        public virtual DbSet<Address> Addresses { get; set; }
        public virtual DbSet<AddressType> AddressTypes { get; set; }
        public virtual DbSet<Application> Applications { get; set; }
        public virtual DbSet<ApplicationContent> ApplicationContents { get; set; }
        public virtual DbSet<ApplicationCountry> ApplicationCountries { get; set; }
        public virtual DbSet<ApplicationDepot> ApplicationDepots { get; set; }
        public virtual DbSet<ApplicationDocument> ApplicationDocuments { get; set; }
        public virtual DbSet<ApplicationIssue> ApplicationIssues { get; set; }
        public virtual DbSet<ApplicationItem> ApplicationItems { get; set; }
        public virtual DbSet<ApplicationLicenseMapping> ApplicationLicenseMappings { get; set; }
        public virtual DbSet<ApplicationType> ApplicationTypes { get; set; }
        public virtual DbSet<AspNetRole> AspNetRoles { get; set; }
        public virtual DbSet<AspNetUserClaim> AspNetUserClaims { get; set; }
        public virtual DbSet<AspNetUserLogin> AspNetUserLogins { get; set; }
        public virtual DbSet<AspNetUser> AspNetUsers { get; set; }
        public virtual DbSet<Bank> Banks { get; set; }
        public virtual DbSet<BankBranch> BankBranches { get; set; }
        public virtual DbSet<BankUser> BankUsers { get; set; }
        public virtual DbSet<BillOfLadingData> BillOfLadingDatas { get; set; }
        public virtual DbSet<Calculator> Calculators { get; set; }
        public virtual DbSet<City> Cities { get; set; }
        public virtual DbSet<CompanyCategory> CompanyCategories { get; set; }
        public virtual DbSet<CompanyDocument> CompanyDocuments { get; set; }
        public virtual DbSet<Country> Countries { get; set; }
        public virtual DbSet<CustomCode> CustomCodes { get; set; }
        public virtual DbSet<Depot> Depots { get; set; }
        public virtual DbSet<DepotDischarge> DepotDischarges { get; set; }
        public virtual DbSet<DepotOwner> DepotOwners { get; set; }
        public virtual DbSet<DepotTrunkedOut> DepotTrunkedOuts { get; set; }
        public virtual DbSet<DischargeParameterAfter> DischargeParameterAfters { get; set; }
        public virtual DbSet<DischargeParameterBefore> DischargeParameterBefores { get; set; }
        public virtual DbSet<Document> Documents { get; set; }
        public virtual DbSet<DocumentIssue> DocumentIssues { get; set; }
        public virtual DbSet<DocumentType> DocumentTypes { get; set; }
        public virtual DbSet<DocumentTypeRight> DocumentTypeRights { get; set; }
        public virtual DbSet<EmployeeDesk> EmployeeDesks { get; set; }
        public virtual DbSet<ExpenditionaryInvoice> ExpenditionaryInvoices { get; set; }
        public virtual DbSet<Faq> Faqs { get; set; }
        public virtual DbSet<FaqCategory> FaqCategories { get; set; }
        public virtual DbSet<Fee> Fees { get; set; }
        public virtual DbSet<FeeType> FeeTypes { get; set; }
        public virtual DbSet<FormMDetail> FormMDetails { get; set; }
        public virtual DbSet<Group> Groups { get; set; }
        public virtual DbSet<ImportApplicationHistory> ImportApplicationHistories { get; set; }
        public virtual DbSet<ImportClass> ImportClasses { get; set; }
        public virtual DbSet<ImportClassificationRequirement> ImportClassificationRequirements { get; set; }
        public virtual DbSet<Importer> Importers { get; set; }
        public virtual DbSet<ImporterAddress> ImporterAddresses { get; set; }
        public virtual DbSet<ImportRequirement> ImportRequirements { get; set; }
        public virtual DbSet<ImportSetting> ImportSettings { get; set; }
        public virtual DbSet<ImportStage> ImportStages { get; set; }
        public virtual DbSet<Invoice> Invoices { get; set; }
        public virtual DbSet<InvoiceItem> InvoiceItems { get; set; }
        public virtual DbSet<Issue> Issues { get; set; }
        public virtual DbSet<IssueCategory> IssueCategories { get; set; }
        public virtual DbSet<IssueLog> IssueLogs { get; set; }
        public virtual DbSet<IssueType> IssueTypes { get; set; }
        public virtual DbSet<Jetty> Jetties { get; set; }
        public virtual DbSet<JettyMapping> JettyMappings { get; set; }
        public virtual DbSet<LabParameter> LabParameters { get; set; }
        public virtual DbSet<Link> Links { get; set; }
        public virtual DbSet<Message> Messages { get; set; }
        public virtual DbSet<MessageTemplate> MessageTemplates { get; set; }
        public virtual DbSet<Notification> Notifications { get; set; }
        public virtual DbSet<NotificationBanker> NotificationBankers { get; set; }
        public virtual DbSet<NotificationCheckList> NotificationCheckLists { get; set; }
        public virtual DbSet<NotificationCheckListOutcome> NotificationCheckListOutcomes { get; set; }
        public virtual DbSet<NotificationDischageData> NotificationDischageDatas { get; set; }
        public virtual DbSet<NotificationDocument> NotificationDocuments { get; set; }
        public virtual DbSet<NotificationHistory> NotificationHistories { get; set; }
        public virtual DbSet<NotificationInspection> NotificationInspections { get; set; }
        public virtual DbSet<NotificationInspectionQueue> NotificationInspectionQueues { get; set; }
        public virtual DbSet<NotificationIssue> NotificationIssues { get; set; }
        public virtual DbSet<NotificationVessel> NotificationVessels { get; set; }
        public virtual DbSet<Page> Pages { get; set; }
        public virtual DbSet<PaymentDetail> PaymentDetails { get; set; }
        public virtual DbSet<Permit> Permits { get; set; }
        public virtual DbSet<PermitApplication> PermitApplications { get; set; }
        public virtual DbSet<Person> People { get; set; }
        public virtual DbSet<Port> Ports { get; set; }
        public virtual DbSet<Process> Processes { get; set; }
        public virtual DbSet<ProcessingHistory> ProcessingHistories { get; set; }
        public virtual DbSet<ProcessTracking> ProcessTrackings { get; set; }
        public virtual DbSet<Product> Products { get; set; }
        public virtual DbSet<ProductBanker> ProductBankers { get; set; }
        public virtual DbSet<ProductColour> ProductColours { get; set; }
        public virtual DbSet<ProductColumn> ProductColumns { get; set; }
        public virtual DbSet<ProductDocumentRequirement> ProductDocumentRequirements { get; set; }
        public virtual DbSet<Recertification> Recertifications { get; set; }
        public virtual DbSet<RecertificationHistory> RecertificationHistories { get; set; }
        public virtual DbSet<RecertificationIssue> RecertificationIssues { get; set; }
        public virtual DbSet<RecertificationProcess> RecertificationProcesses { get; set; }
        public virtual DbSet<RecertificationResult> RecertificationResults { get; set; }
        public virtual DbSet<ReferenceLicense> ReferenceLicenses { get; set; }
        public virtual DbSet<ReferenceLicenseType> ReferenceLicenseTypes { get; set; }
        public virtual DbSet<Region> Regions { get; set; }
        public virtual DbSet<SignOffDocument> SignOffDocuments { get; set; }
        public virtual DbSet<StandardRequirement> StandardRequirements { get; set; }
        public virtual DbSet<StandardRequirementType> StandardRequirementTypes { get; set; }
        public virtual DbSet<Step> Steps { get; set; }
        public virtual DbSet<StepActivityType> StepActivityTypes { get; set; }
        public virtual DbSet<StepsInGroup> StepsInGroups { get; set; }
        public virtual DbSet<StorageProviderRequirement> StorageProviderRequirements { get; set; }
        public virtual DbSet<StorageProviderType> StorageProviderTypes { get; set; }
        public virtual DbSet<StorageTank> StorageTanks { get; set; }
        public virtual DbSet<Structure> Structures { get; set; }
        public virtual DbSet<ThroughPut> ThroughPuts { get; set; }
        public virtual DbSet<Transaction> Transactions { get; set; }
        public virtual DbSet<UnitOfMeasurement> UnitOfMeasurements { get; set; }
        public virtual DbSet<UserLink> UserLinks { get; set; }
        public virtual DbSet<UserProfile> UserProfiles { get; set; }
        public virtual DbSet<Vessel> Vessels { get; set; }
        public virtual DbSet<VesselArrivalDocument> VesselArrivalDocuments { get; set; }
        public virtual DbSet<VesselArrivalNotice> VesselArrivalNotices { get; set; }
        public virtual DbSet<WorkFlow> WorkFlows { get; set; }
        public virtual DbSet<Zone> Zones { get; set; }
    }
}
