//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ImportPermitPortal.EF.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class ImportRequirement
    {
        public long Id { get; set; }
        public int ImportStageId { get; set; }
        public int DocumentTypeId { get; set; }
        public string Remark { get; set; }
    
        public virtual DocumentType DocumentType { get; set; }
        public virtual ImportStage ImportStage { get; set; }
    }
}
