//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ImportPermitPortal.EF.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class InvoiceItem
    {
        public long Id { get; set; }
        public long InvoiceId { get; set; }
        public int FeeId { get; set; }
        public double AmountDue { get; set; }
    
        public virtual Fee Fee { get; set; }
        public virtual Invoice Invoice { get; set; }
    }
}
