//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ImportPermitPortal.EF.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Invoice
    {
        public Invoice()
        {
            this.Applications = new HashSet<Application>();
            this.ExpenditionaryInvoices = new HashSet<ExpenditionaryInvoice>();
            this.InvoiceItems = new HashSet<InvoiceItem>();
            this.Notifications = new HashSet<Notification>();
            this.Transactions = new HashSet<Transaction>();
        }
    
        public long Id { get; set; }
        public string ReferenceCode { get; set; }
        public int PaymentTypeId { get; set; }
        public double TotalAmountDue { get; set; }
        public double AmountPaid { get; set; }
        public int Status { get; set; }
        public string IPAddress { get; set; }
        public System.DateTime DateAdded { get; set; }
        public long ImporterId { get; set; }
        public string RRR { get; set; }
        public Nullable<System.DateTime> ExpiryDate { get; set; }
        public Nullable<int> ServiceDescriptionId { get; set; }
    
        public virtual ICollection<Application> Applications { get; set; }
        public virtual ICollection<ExpenditionaryInvoice> ExpenditionaryInvoices { get; set; }
        public virtual Importer Importer { get; set; }
        public virtual ICollection<InvoiceItem> InvoiceItems { get; set; }
        public virtual ICollection<Notification> Notifications { get; set; }
        public virtual ICollection<Transaction> Transactions { get; set; }
    }
}
