//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ImportPermitPortal.EF.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class IssueType
    {
        public IssueType()
        {
            this.ApplicationIssues = new HashSet<ApplicationIssue>();
            this.DocumentIssues = new HashSet<DocumentIssue>();
            this.NotificationIssues = new HashSet<NotificationIssue>();
            this.RecertificationIssues = new HashSet<RecertificationIssue>();
        }
    
        public int Id { get; set; }
        public string Description { get; set; }
        public string Name { get; set; }
    
        public virtual ICollection<ApplicationIssue> ApplicationIssues { get; set; }
        public virtual ICollection<DocumentIssue> DocumentIssues { get; set; }
        public virtual ICollection<NotificationIssue> NotificationIssues { get; set; }
        public virtual ICollection<RecertificationIssue> RecertificationIssues { get; set; }
    }
}
