//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ImportPermitPortal.EF.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Issue
    {
        public long Id { get; set; }
        public long IssueLogId { get; set; }
        public long AffectedUserId { get; set; }
        public Nullable<long> ResolvedById { get; set; }
        public string Status { get; set; }
    
        public virtual IssueLog IssueLog { get; set; }
        public virtual UserProfile UserProfile { get; set; }
        public virtual UserProfile UserProfile1 { get; set; }
    }
}
