//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ImportPermitPortal.EF.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class IssueLog
    {
        public IssueLog()
        {
            this.Issues = new HashSet<Issue>();
        }
    
        public long Id { get; set; }
        public int IssueCategoryId { get; set; }
        public string Issue { get; set; }
        public System.DateTime DateCreated { get; set; }
        public Nullable<System.DateTime> DateResolved { get; set; }
    
        public virtual ICollection<Issue> Issues { get; set; }
        public virtual IssueCategory IssueCategory { get; set; }
    }
}
