//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ImportPermitPortal.EF.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class NotificationDocument
    {
        public long Id { get; set; }
        public long NotificationId { get; set; }
        public long DocumentId { get; set; }
        public string Comment { get; set; }
        public System.DateTime DateAttached { get; set; }
    
        public virtual Document Document { get; set; }
        public virtual Notification Notification { get; set; }
    }
}
