//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ImportPermitPortal.EF.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class NotificationCheckList
    {
        public NotificationCheckList()
        {
            this.NotificationCheckListOutcomes = new HashSet<NotificationCheckListOutcome>();
        }
    
        public int Id { get; set; }
        public string CheckListItem { get; set; }
        public int DocumentTypeId { get; set; }
    
        public virtual DocumentType DocumentType { get; set; }
        public virtual ICollection<NotificationCheckListOutcome> NotificationCheckListOutcomes { get; set; }
    }
}
