//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ImportPermitPortal.EF.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class NotificationVessel
    {
        public long NotificationVesselId { get; set; }
        public long VesselId { get; set; }
        public long NotificationId { get; set; }
        public int VesselClassTypeId { get; set; }
        public Nullable<System.DateTime> DateAdded { get; set; }
    
        public virtual Notification Notification { get; set; }
        public virtual Vessel Vessel { get; set; }
    }
}
