//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ImportPermitPortal.EF.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class NotificationCheckListOutcome
    {
        public int Id { get; set; }
        public long NotificationId { get; set; }
        public int NotificationCheckListId { get; set; }
        public Nullable<long> EmployeeId { get; set; }
        public Nullable<System.DateTime> Date { get; set; }
        public string Value { get; set; }
        public Nullable<int> Status { get; set; }
    
        public virtual Notification Notification { get; set; }
        public virtual NotificationCheckList NotificationCheckList { get; set; }
    }
}
