//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ImportPermitPortal.EF.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class PaymentDistributionSummary
    {
        public long Id { get; set; }
        public int ServiceId { get; set; }
        public string Beneficiary { get; set; }
        public double Amount { get; set; }
        public string PaymentReference { get; set; }
        public System.DateTime PaymentDate { get; set; }
        public bool Status { get; set; }
    }
}
