//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ImportPermitPortal.EF.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Permit
    {
        public Permit()
        {
            this.Notifications = new HashSet<Notification>();
            this.PermitApplications = new HashSet<PermitApplication>();
        }
    
        public long Id { get; set; }
        public int PermitNo { get; set; }
        public Nullable<System.DateTime> IssueDate { get; set; }
        public Nullable<System.DateTime> ExpiryDate { get; set; }
        public string file { get; set; }
        public string PermitValue { get; set; }
        public int PermitStatus { get; set; }
        public double QuantityImported { get; set; }
        public System.DateTime DateAdded { get; set; }
        public long ImporterId { get; set; }
    
        public virtual Importer Importer { get; set; }
        public virtual ICollection<Notification> Notifications { get; set; }
        public virtual ICollection<PermitApplication> PermitApplications { get; set; }
    }
}
