//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ImportPermitPortal.EF.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class ProductColumn
    {
        public int ProductColumnId { get; set; }
        public long ProductId { get; set; }
        public int CustomCodeId { get; set; }
    
        public virtual CustomCode CustomCode { get; set; }
        public virtual Product Product { get; set; }
    }
}
