//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ImportPermitPortal.EF.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Product
    {
        public Product()
        {
            this.ApplicationDepots = new HashSet<ApplicationDepot>();
            this.ApplicationItems = new HashSet<ApplicationItem>();
            this.Notifications = new HashSet<Notification>();
            this.NotificationBankers = new HashSet<NotificationBanker>();
            this.NotificationInspections = new HashSet<NotificationInspection>();
            this.ProductColumns = new HashSet<ProductColumn>();
            this.ProductDocumentRequirements = new HashSet<ProductDocumentRequirement>();
            this.StorageTanks = new HashSet<StorageTank>();
            this.ThroughPuts = new HashSet<ThroughPut>();
            this.VesselArrivalNotices = new HashSet<VesselArrivalNotice>();
        }
    
        public long ProductId { get; set; }
        public string Code { get; set; }
        public string Name { get; set; }
        public bool Availability { get; set; }
    
        public virtual ICollection<ApplicationDepot> ApplicationDepots { get; set; }
        public virtual ICollection<ApplicationItem> ApplicationItems { get; set; }
        public virtual ICollection<Notification> Notifications { get; set; }
        public virtual ICollection<NotificationBanker> NotificationBankers { get; set; }
        public virtual ICollection<NotificationInspection> NotificationInspections { get; set; }
        public virtual ICollection<ProductColumn> ProductColumns { get; set; }
        public virtual ICollection<ProductDocumentRequirement> ProductDocumentRequirements { get; set; }
        public virtual ICollection<StorageTank> StorageTanks { get; set; }
        public virtual ICollection<ThroughPut> ThroughPuts { get; set; }
        public virtual ICollection<VesselArrivalNotice> VesselArrivalNotices { get; set; }
    }
}
