//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ImportPermitPortal.EF.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Recertification
    {
        public Recertification()
        {
            this.RecertificationHistories = new HashSet<RecertificationHistory>();
            this.RecertificationIssues = new HashSet<RecertificationIssue>();
            this.RecertificationProcesses = new HashSet<RecertificationProcess>();
        }
    
        public long Id { get; set; }
        public string ReferenceCode { get; set; }
        public long NotificationId { get; set; }
        public Nullable<int> Status { get; set; }
        public Nullable<System.DateTime> DateApplied { get; set; }
        public Nullable<System.DateTime> LastModified { get; set; }
    
        public virtual Notification Notification { get; set; }
        public virtual ICollection<RecertificationHistory> RecertificationHistories { get; set; }
        public virtual ICollection<RecertificationIssue> RecertificationIssues { get; set; }
        public virtual ICollection<RecertificationProcess> RecertificationProcesses { get; set; }
    }
}
