//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ImportPermitPortal.EF.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class ReferenceLicense
    {
        public ReferenceLicense()
        {
            this.ApplicationLicenseMappings = new HashSet<ApplicationLicenseMapping>();
        }
    
        public long Id { get; set; }
        public int ReferenceLicenseTypeId { get; set; }
        public string LicenceCode { get; set; }
        public System.DateTime IssueDate { get; set; }
        public System.DateTime ExpiryDate { get; set; }
        public int Status { get; set; }
        public long ImporterId { get; set; }
    
        public virtual ICollection<ApplicationLicenseMapping> ApplicationLicenseMappings { get; set; }
        public virtual Importer Importer { get; set; }
        public virtual ReferenceLicenseType ReferenceLicenseType { get; set; }
    }
}
