//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ImportPermitPortal.EF.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class StandardRequirement
    {
        public long Id { get; set; }
        public int StandardRequirementTypeId { get; set; }
        public long ImporterId { get; set; }
        public string DocumentPath { get; set; }
        public System.DateTime ValidFrom { get; set; }
        public Nullable<System.DateTime> ValidTo { get; set; }
        public System.DateTime LastUpdated { get; set; }
        public string Title { get; set; }
    
        public virtual Importer Importer { get; set; }
        public virtual StandardRequirementType StandardRequirementType { get; set; }
    }
}
