//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ImportPermitPortal.EF.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class StepActivityType
    {
        public StepActivityType()
        {
            this.EmployeeDesks = new HashSet<EmployeeDesk>();
            this.Steps = new HashSet<Step>();
        }
    
        public int Id { get; set; }
        public string Name { get; set; }
        public string Description { get; set; }
    
        public virtual ICollection<EmployeeDesk> EmployeeDesks { get; set; }
        public virtual ICollection<Step> Steps { get; set; }
    }
}
