//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ImportPermitPortal.EF.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Step
    {
        public Step()
        {
            this.NotificationHistories = new HashSet<NotificationHistory>();
            this.NotificationInspectionQueues = new HashSet<NotificationInspectionQueue>();
            this.ProcessingHistories = new HashSet<ProcessingHistory>();
            this.ProcessTrackings = new HashSet<ProcessTracking>();
            this.RecertificationHistories = new HashSet<RecertificationHistory>();
            this.RecertificationProcesses = new HashSet<RecertificationProcess>();
        }
    
        public int Id { get; set; }
        public string Name { get; set; }
        public int ProcessId { get; set; }
        public Nullable<int> SequenceNumber { get; set; }
        public int GroupId { get; set; }
        public Nullable<int> StatusId { get; set; }
        public int ActivityTypeId { get; set; }
        public string Instructions { get; set; }
        public Nullable<int> ExpectedDeliveryDuration { get; set; }
        public Nullable<bool> IsLocationRequired { get; set; }
    
        public virtual Group Group { get; set; }
        public virtual ICollection<NotificationHistory> NotificationHistories { get; set; }
        public virtual ICollection<NotificationInspectionQueue> NotificationInspectionQueues { get; set; }
        public virtual Process Process { get; set; }
        public virtual ICollection<ProcessingHistory> ProcessingHistories { get; set; }
        public virtual ICollection<ProcessTracking> ProcessTrackings { get; set; }
        public virtual ICollection<RecertificationHistory> RecertificationHistories { get; set; }
        public virtual ICollection<RecertificationProcess> RecertificationProcesses { get; set; }
        public virtual StepActivityType StepActivityType { get; set; }
    }
}
