//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ImportPermitPortal.EF.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Transaction
    {
        public Transaction()
        {
            this.PaymentDetails = new HashSet<PaymentDetail>();
        }
    
        public long Id { get; set; }
        public int TransactionTypeId { get; set; }
        public long InvoiceId { get; set; }
        public double Amount { get; set; }
        public System.DateTime PaymentDate { get; set; }
        public string TransactionReference { get; set; }
        public int TransactionMethodId { get; set; }
        public string Remark { get; set; }
        public System.DateTime DateAdded { get; set; }
    
        public virtual Invoice Invoice { get; set; }
        public virtual ICollection<PaymentDetail> PaymentDetails { get; set; }
    }
}
