//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ImportPermitPortal.EF.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class UserProfile
    {
        public UserProfile()
        {
            this.AspNetUsers = new HashSet<AspNetUser>();
            this.BankUsers = new HashSet<BankUser>();
            this.DocumentIssues = new HashSet<DocumentIssue>();
            this.EmployeeDesks = new HashSet<EmployeeDesk>();
            this.Issues = new HashSet<Issue>();
            this.Issues1 = new HashSet<Issue>();
            this.Messages = new HashSet<Message>();
            this.NotificationBankers = new HashSet<NotificationBanker>();
            this.Pages = new HashSet<Page>();
            this.SignOffDocuments = new HashSet<SignOffDocument>();
        }
    
        public long Id { get; set; }
        public bool IsActive { get; set; }
        public long PersonId { get; set; }
        public bool IsAdmin { get; set; }
        public Nullable<bool> IsFirstLogin { get; set; }
    
        public virtual ICollection<AspNetUser> AspNetUsers { get; set; }
        public virtual ICollection<BankUser> BankUsers { get; set; }
        public virtual ICollection<DocumentIssue> DocumentIssues { get; set; }
        public virtual ICollection<EmployeeDesk> EmployeeDesks { get; set; }
        public virtual ICollection<Issue> Issues { get; set; }
        public virtual ICollection<Issue> Issues1 { get; set; }
        public virtual ICollection<Message> Messages { get; set; }
        public virtual ICollection<NotificationBanker> NotificationBankers { get; set; }
        public virtual ICollection<Page> Pages { get; set; }
        public virtual Person Person { get; set; }
        public virtual ICollection<SignOffDocument> SignOffDocuments { get; set; }
    }
}
