//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ImportPermitPortal.EF.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class VesselArrivalNotice
    {
        public VesselArrivalNotice()
        {
            this.VesselArrivalDocuments = new HashSet<VesselArrivalDocument>();
        }
    
        public long VesselArrivalNoticeId { get; set; }
        public string ShipmentIdentitificationNo { get; set; }
        public long ProductId { get; set; }
        public long Quantity { get; set; }
        public System.DateTime ArrivalDate { get; set; }
        public System.DateTime DishargeDate { get; set; }
        public long MotherVesselId { get; set; }
        public Nullable<long> ShuttleVesselId { get; set; }
    
        public virtual Product Product { get; set; }
        public virtual Vessel Vessel { get; set; }
        public virtual ICollection<VesselArrivalDocument> VesselArrivalDocuments { get; set; }
    }
}
