//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ImportPermitPortal.EF.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Vessel
    {
        public Vessel()
        {
            this.NotificationDischageDatas = new HashSet<NotificationDischageData>();
            this.NotificationVessels = new HashSet<NotificationVessel>();
            this.VesselArrivalNotices = new HashSet<VesselArrivalNotice>();
        }
    
        public long VesselId { get; set; }
        public string Name { get; set; }
        public Nullable<double> Capacity { get; set; }
        public System.DateTime DateAdded { get; set; }
        public string VesselLicense { get; set; }
        public Nullable<System.DateTime> IssueDate { get; set; }
        public Nullable<System.DateTime> ExpiryDate { get; set; }
        public Nullable<bool> Status { get; set; }
        public string CompanyName { get; set; }
    
        public virtual ICollection<NotificationDischageData> NotificationDischageDatas { get; set; }
        public virtual ICollection<NotificationVessel> NotificationVessels { get; set; }
        public virtual ICollection<VesselArrivalNotice> VesselArrivalNotices { get; set; }
    }
}
